"""Studio Observability Service — Prometheus & Grafana telemetry engine for BlendEye.
Exposes real-time pipeline performance counters, latency histograms, and alert definitions.
"""

from __future__ import annotations

import logging
import threading
import time
from datetime import UTC, datetime
from typing import Any

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

logger = logging.getLogger(__name__)

# Prometheus Metrics Definitions

# 1. HTTP Traffic & Throughput
HTTP_REQUESTS_TOTAL = Counter(
    "blendeye_http_requests_total",
    "Total HTTP requests received by BlendEye agent services",
    ["method", "endpoint", "status"],
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "blendeye_http_request_duration_seconds",
    "Total HTTP request latency across all endpoints",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

# 1b. Agentic Request Observability by Role & Status Code
HTTP_AGENTIC_REQUESTS_TOTAL = Counter(
    "blendeye_agentic_requests_total",
    "Total HTTP requests received grouped by agentic role and status code",
    ["agentic_use", "status_code", "status_class", "method"],
)

HTTP_AGENTIC_DURATION_SECONDS = Histogram(
    "blendeye_agentic_duration_seconds",
    "Request latency in seconds grouped by agentic role and status class",
    ["agentic_use", "status_class"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

# 2. Gemini Omni Flash & Video Sequencer Pipeline
OMNI_VIDEO_RENDERS_TOTAL = Counter(
    "blendeye_omni_video_renders_total",
    "Total Gemini Omni Flash video generation tasks dispatched",
    ["aspect_ratio", "status"],
)

OMNI_GENERATION_SECONDS = Histogram(
    "blendeye_omni_generation_seconds",
    "Gemini Omni Flash video rendering latency in seconds",
    ["shot_type"],
    buckets=[2.0, 5.0, 10.0, 20.0, 35.0, 60.0, 120.0],
)

PIXEL_ANCHORING_LATENCY_MS = Histogram(
    "blendeye_pixel_anchoring_latency_ms",
    "OpenCV/PIL last-frame extraction latency for sequential video chaining",
    buckets=[5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0],
)

# 3. ClickHouse Sub-Millisecond Time-Gate Operations
CLICKHOUSE_QUERY_LATENCY_MS = Histogram(
    "blendeye_clickhouse_query_latency_ms",
    "Sub-millisecond query latency for ClickHouse time-gate scans",
    buckets=[0.5, 1.0, 2.0, 4.0, 8.0, 15.0, 30.0, 60.0],
)

STORY_EVENTS_GAUGE = Gauge(
    "blendeye_story_events_total",
    "Total number of temporal character knowledge tuples stored in ClickHouse",
)

# 4. Multimodal Audio & Voice Timbre Engine
AUDIO_TTS_SYNTHESIS_SECONDS = Histogram(
    "blendeye_audio_tts_synthesis_seconds",
    "Gemini 3.1 Flash TTS multi-speaker dialogue synthesis duration",
    ["voice_count"],
    buckets=[0.5, 1.0, 2.0, 4.0, 8.0, 15.0],
)

# 5. Parallel Web Systems Search & Grounding
PARALLEL_SEARCH_QUERIES_TOTAL = Counter(
    "blendeye_parallel_search_queries_total",
    "Total open-web search queries dispatched via Parallel Web Systems",
    ["category"],
)

PARALLEL_SEARCH_LATENCY_SECONDS = Histogram(
    "blendeye_parallel_search_latency_seconds",
    "Response latency for Parallel Web Systems search queries in seconds",
    buckets=[0.2, 0.5, 1.0, 2.0, 4.0, 8.0],
)

# 6. Gemini Agent Execution & Script Continuity
AGENT_INFERENCE_DURATION_SECONDS = Histogram(
    "blendeye_agent_inference_duration_seconds",
    "Execution duration for Gemini multimodal agents in seconds",
    ["agent_name"],
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 45.0],
)

CONTINUITY_PARADOXES_TOTAL = Counter(
    "blendeye_continuity_paradoxes_total",
    "Script paradoxes and character knowledge leaks flagged by Script Supervisor",
    ["severity"],
)

# 7. Model Token Consumption & Generative Media Gauges
GEMINI_TOKENS_TOTAL = Counter(
    "blendeye_gemini_tokens_total",
    "Total input/output tokens processed across Gemini 3.7 Flash and Gemini 3.1 Flash TTS",
    ["model", "token_type"],
)

IMAGEN_STORYBOARDS_TOTAL = Counter(
    "blendeye_imagen_storyboards_total",
    "Total anamorphic widescreen storyboards generated by Imagen 3",
    ["aspect_ratio"],
)

ACTIVE_DIRECTORS_GAUGE = Gauge(
    "blendeye_active_directors_total",
    "Number of active concurrent director sessions in BlendEye Studio",
)

PIPELINE_SLO_RATIO_GAUGE = Gauge(
    "blendeye_pipeline_slo_ratio",
    "Percentage of API and agent pipeline requests meeting the <200ms latency target",
)

# 8. Multi-Cloud & Inter-Service Network Round-Trip Latencies (RTT)
NETWORK_RTT_SECONDS = Histogram(
    "blendeye_network_rtt_seconds",
    "Network round-trip latency (RTT) across inter-service and cloud data planes in seconds",
    ["network_type", "service", "destination"],
    buckets=[0.001, 0.005, 0.015, 0.030, 0.060, 0.120, 0.250, 0.500, 1.0],
)

ACTIVE_DIRECTORS_GAUGE.set(1)


def measure_network_latencies() -> list[dict[str, Any]]:
    """Measures real round-trip latency to each external dependency this
    service actually talks to, by issuing a lightweight real request/query
    to each and timing the wall-clock response. Any target that isn't
    configured (missing credentials) or times out is reported as such
    rather than papered over with a synthetic number.
    """
    import httpx

    from app.config import get_settings
    from app.services.clickhouse_store import get_clickhouse_store

    settings = get_settings()
    network_targets: list[dict[str, Any]] = []

    # ClickHouse Cloud — real SELECT 1 round-trip.
    try:
        store = get_clickhouse_store()
        if store.is_connected and store.client is not None:
            t0 = time.time()
            store.client.query("SELECT 1")
            latency_ms = round((time.time() - t0) * 1000, 2)
            CLICKHOUSE_QUERY_LATENCY_MS.observe(latency_ms)
            network_targets.append({
                "network_type": "cloud_database",
                "service": "clickhouse_cloud",
                "destination": settings.clickhouse_host or "unknown",
                "latency_ms": latency_ms,
                "protocol": "TCP / TLS Native Client",
                "status": "healthy",
            })
        else:
            network_targets.append({
                "network_type": "cloud_database",
                "service": "clickhouse_cloud",
                "destination": settings.clickhouse_host or "unconfigured",
                "latency_ms": None,
                "protocol": "TCP / TLS Native Client",
                "status": "not_connected",
            })
    except Exception as e:  # noqa: BLE001
        network_targets.append({
            "network_type": "cloud_database",
            "service": "clickhouse_cloud",
            "destination": settings.clickhouse_host or "unknown",
            "latency_ms": None,
            "protocol": "TCP / TLS Native Client",
            "status": f"error: {e}",
        })

    # Parallel Web Systems — real HEAD request against the API base, only
    # if a key is configured (avoids a network call that can't succeed).
    if settings.parallel_api_key:
        try:
            t0 = time.time()
            resp = httpx.head("https://api.parallel.ai", timeout=5.0)
            latency_ms = round((time.time() - t0) * 1000, 2)
            network_targets.append({
                "network_type": "web_search",
                "service": "parallel_web_api",
                "destination": "api.parallel.ai",
                "latency_ms": latency_ms,
                "protocol": "HTTPS",
                "status": "healthy" if resp.status_code < 500 else f"degraded ({resp.status_code})",
            })
        except Exception as e:  # noqa: BLE001
            network_targets.append({
                "network_type": "web_search",
                "service": "parallel_web_api",
                "destination": "api.parallel.ai",
                "latency_ms": None,
                "protocol": "HTTPS",
                "status": f"unreachable: {e}",
            })
    else:
        network_targets.append({
            "network_type": "web_search",
            "service": "parallel_web_api",
            "destination": "api.parallel.ai",
            "latency_ms": None,
            "protocol": "HTTPS",
            "status": "unconfigured (no PARALLEL_API_KEY)",
        })

    # Grafana Cloud — real HEAD request against the configured Grafana URL.
    if settings.grafana_url:
        try:
            t0 = time.time()
            resp = httpx.head(settings.grafana_url, timeout=5.0)
            latency_ms = round((time.time() - t0) * 1000, 2)
            network_targets.append({
                "network_type": "telemetry_ingest",
                "service": "grafana_cloud",
                "destination": settings.grafana_url,
                "latency_ms": latency_ms,
                "protocol": "HTTPS",
                "status": "healthy" if resp.status_code < 500 else f"degraded ({resp.status_code})",
            })
        except Exception as e:  # noqa: BLE001
            network_targets.append({
                "network_type": "telemetry_ingest",
                "service": "grafana_cloud",
                "destination": settings.grafana_url,
                "latency_ms": None,
                "protocol": "HTTPS",
                "status": f"unreachable: {e}",
            })

    for target in network_targets:
        if target["latency_ms"] is not None:
            NETWORK_RTT_SECONDS.labels(
                network_type=target["network_type"],
                service=target["service"],
                destination=target["destination"],
            ).observe(target["latency_ms"] / 1000.0)

    return network_targets


def get_prometheus_metrics() -> tuple[bytes, str]:
    """Generates the latest Prometheus exposition text."""
    return generate_latest(), CONTENT_TYPE_LATEST


def get_studio_health_status() -> dict[str, Any]:
    """Returns operational status for Grafana observability dashboards, derived
    from actual configuration/connectivity checks rather than hardcoded values.
    """
    from app.config import get_settings
    from app.services.clickhouse_store import get_clickhouse_store

    settings = get_settings()

    try:
        store = get_clickhouse_store()
        clickhouse_status = "connected" if (store.is_connected and store.client is not None) else "not_connected"
    except Exception:  # noqa: BLE001
        clickhouse_status = "error"

    pipeline = {
        "omni_video_sequencer": "configured" if settings.google_api_key else "unconfigured (no GOOGLE_API_KEY)",
        "clickhouse_timegate": clickhouse_status,
        "gemini_agents": "configured" if settings.google_api_key else "unconfigured (no GOOGLE_API_KEY)",
        "parallel_web_search": "configured" if settings.parallel_api_key else "unconfigured (no PARALLEL_API_KEY)",
        "audio_multi_speaker": "configured" if settings.google_api_key else "unconfigured (no GOOGLE_API_KEY)",
        "continuity_supervisor": "configured" if settings.google_api_key else "unconfigured (no GOOGLE_API_KEY)",
    }
    overall_status = "healthy" if all(
        v in ("connected", "configured") for v in pipeline.values()
    ) else "degraded"

    return {
        "status": overall_status,
        "timestamp": time.time(),
        "observability_engine": "Grafana Labs OpenTelemetry Stack",
        "pipeline": pipeline,
        "network_latencies": measure_network_latencies(),
    }


def get_mcp_status() -> dict[str, Any]:
    """Reports whether the MCP servers this service actually shells out to are
    present and configured, derived from real checks rather than asserted
    strings.

    Each entry carries a `verified` flag so callers can tell a real capability
    probe from a config check. `mcp-clickhouse` and `mcp-grafana` are stdio
    subprocesses launched on demand (see clickhouse_mcp.py / grafana_mcp.py),
    so "available" means the console script resolves on PATH — not that a
    session has been established.
    """
    import shutil

    from app.config import get_settings

    settings = get_settings()

    clickhouse_bin = shutil.which("mcp-clickhouse")
    grafana_bin = shutil.which("mcp-grafana")

    if not clickhouse_bin:
        clickhouse_state = "unavailable (mcp-clickhouse not on PATH)"
    elif not settings.clickhouse_host:
        clickhouse_state = "installed, no ClickHouse host configured"
    else:
        clickhouse_state = f"available (read-only, target {settings.clickhouse_host})"

    if not grafana_bin:
        grafana_state = "unavailable (mcp-grafana not on PATH)"
    elif not settings.grafana_service_account_token:
        grafana_state = "installed, no GRAFANA_SERVICE_ACCOUNT_TOKEN configured"
    else:
        grafana_state = "available (service account token configured)"

    return {
        "mcp_clickhouse": {
            "state": clickhouse_state,
            "on_path": bool(clickhouse_bin),
            "allow_write": False,
            "verified": bool(clickhouse_bin and settings.clickhouse_host),
        },
        "mcp_grafana": {
            "state": grafana_state,
            "on_path": bool(grafana_bin),
            "verified": bool(grafana_bin and settings.grafana_service_account_token),
        },
    }


# ============================================================================
# Agentic Request Observability & Classification Engine
# ============================================================================

_AGENTIC_STATS_LOCK = threading.Lock()


def map_endpoint_to_agentic(path: str) -> dict[str, str]:
    """Classifies an HTTP endpoint path into its designated agentic role, human label, and category."""
    clean_path = path.rstrip("/") or "/"
    if clean_path.startswith("/showrunner"):
        return {
            "agentic_use": "showrunner_copilot",
            "label": "Writers' Room Showrunner",
            "category": "Creative Development",
        }
    if clean_path.startswith(("/location", "/location-scout")):
        return {
            "agentic_use": "location_scouting",
            "label": "Location Scout & Precedent Researcher",
            "category": "Research & Grounding",
        }
    if clean_path.startswith("/continuity"):
        return {
            "agentic_use": "continuity_supervisor",
            "label": "Script Continuity Supervisor",
            "category": "Quality & Continuity",
        }
    if clean_path.startswith(("/video-sequence", "/media/video")):
        return {
            "agentic_use": "video_sequencer_omni",
            "label": "Gemini Omni Flash Video Sequencer",
            "category": "Generative Media",
        }
    if clean_path.startswith("/media/tts"):
        return {
            "agentic_use": "audio_dialogue_tts",
            "label": "Gemini 3.1 Flash Multi-Speaker TTS",
            "category": "Generative Media",
        }
    if clean_path.startswith(("/media/image", "/media/storyboard")):
        return {
            "agentic_use": "storyboard_artist_imagen",
            "label": "Imagen 3 Storyboard Artist",
            "category": "Generative Media",
        }
    if clean_path.startswith("/media/music"):
        return {
            "agentic_use": "cinematic_music_composer",
            "label": "Lyria Film Score Composer",
            "category": "Generative Media",
        }
    if clean_path.startswith("/sharding"):
        return {
            "agentic_use": "perspective_sharding",
            "label": "Perspective Sharding Engine",
            "category": "Temporal Memory",
        }
    if clean_path.startswith("/hot-seat"):
        return {
            "agentic_use": "character_actor_hotseat",
            "label": "Hot-Seat Character Actor",
            "category": "Interactive Acting",
        }
    if clean_path.startswith("/script"):
        return {
            "agentic_use": "screenplay_generator",
            "label": "Screenplay Generator & Scene Architect",
            "category": "Creative Development",
        }
    if clean_path.startswith("/sequence"):
        return {
            "agentic_use": "sequence_director",
            "label": "Sequence Structure Director",
            "category": "Creative Development",
        }
    if clean_path.startswith("/bridge"):
        return {
            "agentic_use": "cross_scene_bridge",
            "label": "Cross-Scene Narrative Bridge",
            "category": "Creative Development",
        }
    if clean_path.startswith("/multiverse"):
        return {
            "agentic_use": "multiverse_takes",
            "label": "Multiverse Alternate Takes",
            "category": "Creative Development",
        }
    if clean_path.startswith("/scene-rewrite"):
        return {
            "agentic_use": "scene_rewriter",
            "label": "Scene Polisher & Dialog Doctor",
            "category": "Creative Development",
        }
    if clean_path.startswith("/fusion"):
        return {
            "agentic_use": "film_fusion_crossover",
            "label": "Film Fusion Multiverse Co-Pilot",
            "category": "Creative Development",
        }
    if clean_path.startswith("/character-lab"):
        return {
            "agentic_use": "character_chemistry_lab",
            "label": "Character Chemistry Lab",
            "category": "Creative Development",
        }
    if clean_path.startswith("/style-extractor"):
        return {
            "agentic_use": "style_director",
            "label": "Cinematic Style Director",
            "category": "Creative Development",
        }
    if clean_path.startswith("/shotlist"):
        return {
            "agentic_use": "shot_planner",
            "label": "Cinematographer Shot Planner",
            "category": "Production & Planning",
        }
    if clean_path.startswith("/market-viability"):
        return {
            "agentic_use": "market_predictor",
            "label": "Box Office & Territory Forecaster",
            "category": "Production & Planning",
        }
    if clean_path.startswith("/production"):
        return {
            "agentic_use": "production_manager",
            "label": "Stripboard & Production Scheduler",
            "category": "Production & Planning",
        }
    if clean_path.startswith("/observability"):
        return {
            "agentic_use": "studio_observability",
            "label": "Grafana Studio Telemetry",
            "category": "Telemetry & Ops",
        }
    return {
        "agentic_use": "general_api",
        "label": "Core Studio Gateway",
        "category": "System",
    }


_AGENTIC_CATALOG: list[dict[str, Any]] = [
    {"agentic_use": "showrunner_copilot", "label": "Writers' Room Showrunner", "category": "Creative Development"},
    {"agentic_use": "location_scouting", "label": "Location Scout & Precedent Researcher", "category": "Research & Grounding"},
    {"agentic_use": "continuity_supervisor", "label": "Script Continuity Supervisor", "category": "Quality & Continuity"},
    {"agentic_use": "video_sequencer_omni", "label": "Gemini Omni Flash Video Sequencer", "category": "Generative Media"},
    {"agentic_use": "storyboard_artist_imagen", "label": "Imagen 3 Storyboard Artist", "category": "Generative Media"},
    {"agentic_use": "audio_dialogue_tts", "label": "Gemini 3.1 Flash Multi-Speaker TTS", "category": "Generative Media"},
    {"agentic_use": "cinematic_music_composer", "label": "Lyria Film Score Composer", "category": "Generative Media"},
    {"agentic_use": "character_actor_hotseat", "label": "Hot-Seat Character Actor", "category": "Interactive Acting"},
    {"agentic_use": "perspective_sharding", "label": "Perspective Sharding Engine", "category": "Temporal Memory"},
    {"agentic_use": "screenplay_generator", "label": "Screenplay Generator & Scene Architect", "category": "Creative Development"},
    {"agentic_use": "sequence_director", "label": "Sequence Structure Director", "category": "Creative Development"},
    {"agentic_use": "cross_scene_bridge", "label": "Cross-Scene Narrative Bridge", "category": "Creative Development"},
    {"agentic_use": "multiverse_takes", "label": "Multiverse Alternate Takes", "category": "Creative Development"},
    {"agentic_use": "scene_rewriter", "label": "Scene Polisher & Dialog Doctor", "category": "Creative Development"},
    {"agentic_use": "film_fusion_crossover", "label": "Film Fusion Multiverse Co-Pilot", "category": "Creative Development"},
    {"agentic_use": "character_chemistry_lab", "label": "Character Chemistry Lab", "category": "Creative Development"},
    {"agentic_use": "style_director", "label": "Cinematic Style Director", "category": "Creative Development"},
    {"agentic_use": "shot_planner", "label": "Cinematographer Shot Planner", "category": "Production & Planning"},
    {"agentic_use": "market_predictor", "label": "Box Office & Territory Forecaster", "category": "Production & Planning"},
    {"agentic_use": "production_manager", "label": "Stripboard & Production Scheduler", "category": "Production & Planning"},
    {"agentic_use": "studio_observability", "label": "Grafana Studio Telemetry", "category": "Telemetry & Ops"},
]

_AGENTIC_STATS: dict[str, dict[str, Any]] = {}


def _init_agentic_stats():
    for item in _AGENTIC_CATALOG:
        use = item["agentic_use"]
        _AGENTIC_STATS[use] = {
            "agentic_use": use,
            "label": item["label"],
            "category": item["category"],
            "total_calls": 0,
            "status_codes": {},
            "status_classes": {"2xx": 0, "4xx": 0, "5xx": 0},
            "last_status": None,
            "last_latency_ms": None,
            "avg_latency_ms": None,
            "last_request_at": None,
        }


_init_agentic_stats()


def record_agentic_request(endpoint: str, method: str, status_code: int, duration_sec: float) -> None:
    """Records an incoming request against its classified agentic use and HTTP status code."""
    meta = map_endpoint_to_agentic(endpoint)
    use = meta["agentic_use"]
    code_str = str(status_code)
    status_class = f"{code_str[0]}xx" if len(code_str) >= 3 else "unknown"
    duration_ms = round(duration_sec * 1000, 2)
    now_iso = datetime.now(UTC).isoformat()

    try:
        HTTP_AGENTIC_REQUESTS_TOTAL.labels(
            agentic_use=use,
            status_code=code_str,
            status_class=status_class,
            method=method,
        ).inc()
        HTTP_AGENTIC_DURATION_SECONDS.labels(
            agentic_use=use,
            status_class=status_class,
        ).observe(duration_sec)
    except Exception as e:  # noqa: BLE001
        # Prometheus label registration is best-effort; a metrics failure must
        # never break the request path it is instrumenting.
        logger.debug("Failed to record Prometheus agentic counters: %s", e)

    with _AGENTIC_STATS_LOCK:
        if use not in _AGENTIC_STATS:
            _AGENTIC_STATS[use] = {
                "agentic_use": use,
                "label": meta["label"],
                "category": meta["category"],
                "total_calls": 0,
                "status_codes": {},
                "status_classes": {"2xx": 0, "4xx": 0, "5xx": 0},
                "last_status": status_code,
                "last_latency_ms": duration_ms,
                "avg_latency_ms": duration_ms,
                "last_request_at": now_iso,
            }

        entry = _AGENTIC_STATS[use]
        entry["total_calls"] += 1
        entry["status_codes"][code_str] = entry["status_codes"].get(code_str, 0) + 1
        entry["status_classes"][status_class] = entry["status_classes"].get(status_class, 0) + 1
        entry["last_status"] = status_code
        entry["last_latency_ms"] = duration_ms
        prev_calls = entry["total_calls"] - 1
        if prev_calls > 0 and entry.get("avg_latency_ms") is not None:
            entry["avg_latency_ms"] = round(
                (entry["avg_latency_ms"] * prev_calls + duration_ms) / entry["total_calls"], 2
            )
        else:
            entry["avg_latency_ms"] = duration_ms
        entry["last_request_at"] = now_iso


def get_agentic_requests_summary() -> dict[str, Any]:
    """Returns an aggregated snapshot of requests grouped by agentic role and status codes."""
    with _AGENTIC_STATS_LOCK:
        roles_list: list[dict[str, Any]] = []
        total_requests = 0
        status_classes_total = {"2xx": 0, "4xx": 0, "5xx": 0}
        status_codes_total: dict[str, int] = {}

        for entry in _AGENTIC_STATS.values():
            calls = entry["total_calls"]
            total_requests += calls
            for sc, count in entry["status_codes"].items():
                status_codes_total[sc] = status_codes_total.get(sc, 0) + count
            for sclass, count in entry["status_classes"].items():
                status_classes_total[sclass] = status_classes_total.get(sclass, 0) + count

            success_calls = entry["status_classes"].get("2xx", 0)
            rate = round((success_calls / calls * 100), 1) if calls > 0 else 100.0

            roles_list.append({
                **entry,
                "success_rate": rate,
            })

        roles_list.sort(key=lambda r: r["total_calls"], reverse=True)

        overall_2xx = status_classes_total.get("2xx", 0)
        overall_success_rate = (
            round((overall_2xx / total_requests * 100), 1) if total_requests > 0 else 100.0
        )

        return {
            "total_requests": total_requests,
            "success_rate_percent": overall_success_rate,
            "status_classes": status_classes_total,
            "status_codes": status_codes_total,
            "roles": roles_list,
        }



